const state = {
  events: [
    false,
    "Bachata",
    "Salsa & Zouk",
    false,
    "Bachata & Salsa",
    false,
    false,
  ],

  workers: [
    {
      id: "tanya123",
      name: "Tanya",
      email: "tanya9kin@gmail.com",
      bachata: {
        level1: true,
        level2: true,
        level3: true,
        level4: true,
        level5: false,
        dj: false,
      },
      salsa: false,
      zouk: { level1: true, level2: true, level3: false, dj: false },
    },
    {
      id: "daniel123",
      name: "Daniel",
      email: "daniel@gmail.com",
      bachata: {
        level1: true,
        level2: true,
        level3: true,
        level4: false,
        level5: false,
        dj: true,
      },
      salsa: false,
      zouk: { level1: true, level2: true, level3: true, dj: true },
    },
    {
      id: "lior123",
      name: "Lior",
      email: "lior@gmail.com",
      bachata: {
        level1: true,
        level2: true,
        level3: true,
        level4: true,
        level5: true,
        dj: false,
      },
      salsa: {
        level1: true,
        level2: true,
        level3: false,
        level4: false,
        level5: false,
        dj: false,
      },
      zouk: false,
    },
    {
      id: "hezi123",
      name: "Hezi",
      email: "hezi@gmail.com",
      bachata: {
        level1: true,
        level2: true,
        level3: true,
        level4: true,
        level5: true,
        dj: false,
      },
      salsa: {
        level1: true,
        level2: true,
        level3: false,
        level4: false,
        level5: false,
        dj: false,
      },
      zouk: false,
    },
    {
      id: "bathen123",
      name: "Bat-hen",
      email: "bat-hen@gmail.com",
      bachata: false,
      salsa: {
        level1: true,
        level2: true,
        level3: false,
        level4: false,
        level5: false,
        dj: false,
      },
      zouk: false,
    },
    {
      id: "haim123",
      name: "Haim",
      email: "haim@gmail.com",
      bachata: {
        level1: true,
        level2: true,
        level3: true,
        level4: false,
        level5: false,
        dj: false,
      },
      salsa: {
        level1: true,
        level2: true,
        level3: true,
        level4: true,
        level5: false,
        dj: false,
      },
      zouk: false,
    },
    {
      id: "or123",
      name: "Don Or",
      bachata: {
        level1: false,
        level2: false,
        level3: false,
        level4: false,
        level5: false,
        dj: true,
      },
      salsa: false,
      zouk: false,
    },
    {
      id: "vova123",
      name: "Vova",
      bachata: false,
      salsa: {
        level1: true,
        level2: true,
        level3: true,
        level4: true,
        level5: true,
        dj: true,
      },
      zouk: false,
    },
  ],

  chosen_day: 25,

  chosen_day_schedule: {
    bachata: {
      level1: "Tanya",
      level2: "Hezi",
      level3: "Lior",
      dj: "Don Or",
    },
    salsa: {
      level1: "Bat-hen",
      level2: "Haim",
      dj: "Vova",
    },
  },

  events: [
    {
      id: 1,
      date: new Date("2023-06-26"),
      type: "Bachata",
      workers: [
        {
          id: 1,
          first_name: "Tanya",
          last_name: "Deveykin",
          imageUrl:
            "https://scontent.ftlv5-1.fna.fbcdn.net/v/t39.30808-6/355372933_10160618490265837_2436940194642292552_n.jpg?_nc_cat=105&cb=99be929b-3346023f&ccb=1-7&_nc_sid=09cbfe&_nc_ohc=qzfKoN_QkeMAX_ilrgi&_nc_ht=scontent.ftlv5-1.fna&oh=00_AfCUxAQ71T1VbI3b4WVcL94JUZFz6auS4CZ4daRrU7yZQg&oe=649F23A5",
          level: 1,
          class: 1,
        },
        {
          id: 2,
          first_name: "Lior",
          last_name: "Benisty",
          imageUrl: undefined,
          level: 2,
          class: 1,
        },
        {
          id: 3,
          first_name: "Hezi",
          last_name: "Ciporin",
          imageUrl: undefined,
          level: 3,
          class: 4,
        },
        {
          id: 4,
          first_name: "Dor",
          last_name: "Vardi",
          imageUrl: undefined,
          level: 4,
          class: 10,
        },
        {
          id: 5,
          first_name: "Jordan",
          last_name: "Perez",
          imageUrl: undefined,
          level: 5,
          class: 0,
        },
      ],
    },
    { id: 2, date: new Date("2023-06-26"), type: "Barman" },
    {
      id: 3,
      date: new Date("2023-06-29"),
      type: "Bachata",
      workers: [
        {
          id: 6,
          first_name: "Lior",
          last_name: "Benisti",
          imageUrl: undefined,
          level: 2,
          class: 2,
        },
      ],
    },
    { id: 4, date: new Date("2023-06-29"), type: "Salsa" },
    // { id: 5, date: new Date("2023-06-29"), type: "Barman" },
    { id: 6, date: new Date("2023-06-29"), type: "Advertisment" },
    { id: 7, date: new Date("2023-07-05"), type: "zouk" },
    { id: 8, date: new Date("2023-07-05"), type: "Salsa" },
    // { id: 9, date: new Date("2023-07-05"), type: "Barman" },
    { id: 10, date: new Date("2023-07-05"), type: "Advertisment" },
  ],
};

module.exports = state;
